### ISSUE TITLE
Add description in Readme.md

### ISSUE THREAD

**Issue by the94air** [PHPJunior/laravel-html-encrypt#1]
Can you give use more explanation what does this package do and how it work? thanks so much.

**Comment by ctf0** [comment]
the package adds 

https://github.com/PHPJunior/laravel-html-encrypt/blob/4809b5830c7214362e2c2e39b7f428d9f78083ce/src/Middleware/HtmlEncrypt.php#L50-L58

on each response so you cant use any of the keys in the config, still not sure why this is needed though.

**Comment by the94air** [comment]
Yea, I mean.. I can access page HTML code using postman. Right?. But this still a good solution for browser users.

### Update:
This trick does not even let you see the code in postman chrome app.
